when:
  event: [push, manual]
  branch: main

steps:
  - name: publish/cloudfront
    image: amazon/aws-cli:2.15.50
    commands:
      - aws cloudfront create-invalidation --distribution-id $${CLOUDFRONT_DISTRIBUTION} --paths '/*'
    secrets:
      - S3_BUCKET
      - CLOUDFRONT_DISTRIBUTION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    depends_on: [ build ]
